/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.mariuszgromada.math.mxparser.Argument;
import org.mariuszgromada.math.mxparser.Expression;

/**
 *
 * @author geezylucas
 */
public class FormIntegracion extends javax.swing.JFrame {

    private int k;
    private int c;
    private int n;
    private double redon;
    private int i;
    private double ec;
    private double suma;
    private final double[] integra = new double[2000];
    private final double[] erro = new double[2000];
    private double a;
    private double b;
    private double h;
    private double j;
    private double m;
    private double a1;
    private double b1;
    private double m1;

    /**
     * Creates new form FormIntegracion
     */
    public FormIntegracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSoluciones = new javax.swing.ButtonGroup();
        jtfTextFunction = new javax.swing.JTextField();
        jtfTextA = new javax.swing.JTextField();
        jtfTextB = new javax.swing.JTextField();
        jlblFunction = new javax.swing.JLabel();
        jlblTextA = new javax.swing.JLabel();
        jlblTextB = new javax.swing.JLabel();
        jlblCifras = new javax.swing.JLabel();
        jtfTextC = new javax.swing.JTextField();
        jtfTextBG = new javax.swing.JTextField();
        jlblRangoG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfTextAG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSalida = new javax.swing.JTable();
        jplChart = new javax.swing.JPanel();
        jbtnCalcular = new javax.swing.JButton();
        jbtnGraficar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jrbtnRectangulos = new javax.swing.JRadioButton();
        jrbtnTrapecios = new javax.swing.JRadioButton();
        jrbtnSimpson = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblFunction.setText("Dame función:");

        jlblTextA.setText("Dame a:");

        jlblTextB.setText("Dame b:");

        jlblCifras.setText("<html>Dame cifras<br>significativas:</html>");

        jlblRangoG.setText("<html>Dame rango<br>de la gráfica:</html>");

        jLabel1.setText("a");

        jtSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "Integral", "Error"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtSalida);

        javax.swing.GroupLayout jplChartLayout = new javax.swing.GroupLayout(jplChart);
        jplChart.setLayout(jplChartLayout);
        jplChartLayout.setHorizontalGroup(
            jplChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jplChartLayout.setVerticalGroup(
            jplChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jbtnCalcular.setText("Calcular");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        jbtnGraficar.setText("Graficar");
        jbtnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGraficarActionPerformed(evt);
            }
        });

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel2.setText("Aproximación de área bajo la curva");

        btngSoluciones.add(jrbtnRectangulos);
        jrbtnRectangulos.setText("Rectángulos");

        btngSoluciones.add(jrbtnTrapecios);
        jrbtnTrapecios.setText("Trapecios");

        btngSoluciones.add(jrbtnSimpson);
        jrbtnSimpson.setText("Simpson 1/3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblRangoG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblCifras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblTextA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblTextB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblFunction, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfTextAG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfTextBG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfTextC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfTextB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfTextFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnGraficar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jplChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbtnSimpson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtnTrapecios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtnRectangulos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbtnRectangulos)
                    .addComponent(jrbtnTrapecios)
                    .addComponent(jrbtnSimpson))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblFunction)
                            .addComponent(jbtnCalcular)
                            .addComponent(jtfTextFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTextA)
                            .addComponent(jbtnGraficar))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTextB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnLimpiar)
                            .addComponent(jtfTextB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCifras)
                            .addComponent(jtfTextC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblRangoG)
                            .addComponent(jtfTextBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtfTextAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addComponent(jplChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayChart(XYDataset dataset0, XYDataset dataset1) {
        createChart(dataset0, dataset1);

        ChartPanel chartPanel = new ChartPanel(chart) {

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(396, 408);
            }
        };
        chartPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        chartPanel.setBackground(Color.white);
        add(chartPanel);

        jplChart.setLayout(new java.awt.BorderLayout());
        jplChart.add(chartPanel, BorderLayout.CENTER);
        jplChart.validate();
    }

    private void createChart(XYDataset dataset0, XYDataset dataset1) {

        JFreeChart chartDirty = ChartFactory.createXYStepAreaChart(
                "XY Area", // Chart Title
                null, // X-Axis Label
                null, // Y-Axis Label
                dataset0
        );
        XYPlot plot = (XYPlot) chartDirty.getPlot();

        XYLineAndShapeRenderer render1 = new XYLineAndShapeRenderer(true, false);
        plot.setDataset(1, dataset1);
        plot.setRenderer(1, render1);

        plot.setBackgroundPaint(Color.WHITE);

        plot.setRangeGridlinesVisible(true);
        plot.setRangeGridlinePaint(Color.BLACK);

        plot.setDomainGridlinesVisible(true);
        plot.setDomainGridlinePaint(Color.BLACK);

        chartDirty.getLegend().setFrame(BlockBorder.NONE);

        chart = new JFreeChart("Gráfica", JFreeChart.DEFAULT_TITLE_FONT, plot, true);
    }

    private double f(double x) {
        Argument varX = new Argument("x = " + x);

        Expression e = new Expression(jtfTextFunction.getText(), varX);
        double result = e.calculate();
        return result;
    }

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jtSalida.getModel();
        model.setRowCount(0);

        a = Double.parseDouble(jtfTextA.getText());
        b = Double.parseDouble(jtfTextB.getText());
        c = Integer.parseInt(jtfTextC.getText());
        ec = 0.5 * Math.pow(10, -c);
        redon = Math.pow(10, c + 2);
        erro[i] = 1;
        suma = 0;

        if (jrbtnRectangulos.isSelected()) {
            // Rectangulos
            n = 100;
            h = (b - a) / n;

            for (k = 0; k <= n - 1; k++) {
                suma = suma + h * f(a + k * h);
            }
        } else if (jrbtnTrapecios.isSelected()) {
            // Trapecios
            n = 10;
            h = (b - a) / n;

            for (k = 1; k <= n - 1; k++) {
                suma = suma + f(a + k * h);
            }
            suma = (h / 2) * (f(a) + f(b) + (2 * suma));
        } else if (jrbtnSimpson.isSelected()) {
            // Simpson
            n = 4;
            h = (b - a) / (2 * n);

            for (k = 1; k <= n; k++) {
                suma = suma + ((2 * f(a + (((2 * k) - 1) * h))) + f(a + (2 * k * h)));
            }
            suma = (h / 3) * (f(a) - f(b) + (2 * suma));

        }

        integra[i] = suma;
        // imprimir los renglones
        model.addRow(new Object[]{
            n,
            (Math.round(integra[i] * redon) / redon),
            (Math.round(erro[i] * redon) / redon)
        });

        while (erro[i] > ec) {
            i++;
            suma = 0;

            if (jrbtnRectangulos.isSelected()) {
                n = n + 100;
                h = (b - a) / n;

                for (k = 0; k <= n - 1; k++) {
                    suma = suma + h * f(a + k * h);
                }
            } else if (jrbtnTrapecios.isSelected()) {
                n = n + 10;
                h = (b - a) / n;

                for (k = 1; k <= n - 1; k++) {
                    suma = suma + f(a + k * h);
                }
                suma = (h / 2) * (f(a) + f(b) + (2 * suma));
            } else if (jrbtnSimpson.isSelected()) {
                n = n + 4;
                h = (b - a) / (2 * n);

                for (k = 1; k <= n; k++) {
                    suma = suma + ((2 * f(a + (((2 * k) - 1) * h))) + f(a + (2 * k * h)));
                }
                suma = (h / 3) * (f(a) - f(b) + (2 * suma));
            }

            integra[i] = suma;
            erro[i] = Math.abs((integra[i] - integra[i - 1]) / integra[i]);

            model.addRow(new Object[]{
                n,
                (Math.round(integra[i] * redon) / redon),
                (Math.round(erro[i] * redon) / redon)
            });
        }
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jtSalida.getModel();

        model.setRowCount(0);

        jtfTextA.setText("");
        jtfTextB.setText("");
        jtfTextC.setText("");
        jtfTextAG.setText("");
        jtfTextBG.setText("");
        jtfTextFunction.setText("");
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGraficarActionPerformed
        // TODO add your handling code here:
        a1 = Double.parseDouble(jtfTextAG.getText());
        b1 = Double.parseDouble(jtfTextBG.getText());

        j = a1;

        XYSeriesCollection dataset0 = new XYSeriesCollection();
        XYSeriesCollection dataset1 = new XYSeriesCollection();

        XYSeries seriesFunction = new XYSeries("Function", false);
        XYSeries seriesArea = new XYSeries("Area", false);

        while (j <= b1) {
            seriesFunction.add((Math.round(j * 10.0) / 10.0), f(j));
            j = j + 0.1;
        }

        m = a;

        while (m <= b) {
            seriesArea.add((Math.round(m * 10.0) / 10.0), f(m));
            m = m + 0.1;
        }

        dataset0.addSeries(seriesFunction);
        dataset1.addSeries(seriesArea);

        jplChart.removeAll();
        displayChart(dataset1, dataset0);
    }//GEN-LAST:event_jbtnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIntegracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormIntegracion().setVisible(true);
        });
    }

    private JFreeChart chart;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngSoluciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnGraficar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JLabel jlblCifras;
    private javax.swing.JLabel jlblFunction;
    private javax.swing.JLabel jlblRangoG;
    private javax.swing.JLabel jlblTextA;
    private javax.swing.JLabel jlblTextB;
    private javax.swing.JPanel jplChart;
    private javax.swing.JRadioButton jrbtnRectangulos;
    private javax.swing.JRadioButton jrbtnSimpson;
    private javax.swing.JRadioButton jrbtnTrapecios;
    private javax.swing.JTable jtSalida;
    private javax.swing.JTextField jtfTextA;
    private javax.swing.JTextField jtfTextAG;
    private javax.swing.JTextField jtfTextB;
    private javax.swing.JTextField jtfTextBG;
    private javax.swing.JTextField jtfTextC;
    private javax.swing.JTextField jtfTextFunction;
    // End of variables declaration//GEN-END:variables
}
